repos:
-   repo: local
    hooks:
    - id: java-format
      name: java-format
      entry: ./.scripts/java-precommit-hook.sh
      language: system
      'types_or': [java]
      args: ["git", "--replace"]
      require_serial: false
      additional_dependencies: []
      minimum_pre_commit_version: 2.9.2
